; Inno Setup script — Bank Statement Format Studio (per-user install, offline).
; Build after PyInstaller:  iscc packaging\installer.iss
; Signing: V1 ships UNSIGNED per docs/UNSIGNED-RELEASE-POLICY.md — never fake
; a signature or present the installer as signed. If the owner later obtains a
; certificate (Trusted Signing/OV), configure the SignTool hook below.

#define AppName "Bank Statement Format Studio"
#define AppVersion "1.0.0"
#define AppPublisher "Leela Aravind Karlapudi"
#define DistDir "dist\\BankFormatStudio"

[Setup]
AppId={{6E7B62F1-9C64-4A7E-A87A-BFS0V1000001}}
AppName={#AppName}
AppVersion={#AppVersion}
AppPublisher={#AppPublisher}
AppCopyright=Copyright (C) 2026 {#AppPublisher}
DefaultDirName={autopf}\{#AppName}
; SEC-22: per-user install, no elevation
PrivilegesRequired=lowest
DisableProgramGroupPage=yes
OutputBaseFilename=BankFormatStudio-{#AppVersion}-setup
; Product icon (generated by tools/make_icon.py from assets/logo/logo.png);
; shortcuts inherit the icon embedded in BankFormatStudio.exe via bfs.spec.
SetupIconFile=logo.ico
UninstallDisplayIcon={app}\BankFormatStudio.exe
; EULA shown before installation; Inno Setup requires acceptance to proceed.
; It governs the proprietary Software only and does not override the
; third-party licences shipped in THIRD-PARTY-NOTICES.txt / licenses\.
LicenseFile=EULA.txt
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
; No network access anywhere in the installer (fully offline).
; OWNER ACTION: uncomment when signing is configured
; SignTool=bfs_sign $f

[Files]
Source: "{#DistDir}\*"; DestDir: "{app}"; Flags: recursesubdirs ignoreversion
Source: "EULA.txt"; DestDir: "{app}"; Flags: ignoreversion
; LGPL obligation artefacts must ship in the install dir:
Source: "THIRD-PARTY-NOTICES.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "licenses\*"; DestDir: "{app}\licenses"; Flags: recursesubdirs ignoreversion
Source: "..\docs\CSV-DIALECT.md"; DestDir: "{app}\docs"; Flags: ignoreversion

[Icons]
Name: "{autoprograms}\{#AppName}"; Filename: "{app}\BankFormatStudio.exe"
Name: "{autodesktop}\{#AppName}"; Filename: "{app}\BankFormatStudio.exe"; Tasks: desktopicon

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop shortcut"; Flags: unchecked

[Run]
Filename: "{app}\BankFormatStudio.exe"; Description: "Launch {#AppName}"; Flags: nowait postinstall skipifsilent
